[supervisord]
nodaemon=true

[program:xvfb]
command=Xvfb :99 -screen 0 1024x768x24 -ac
autorestart=true
priority=10

[program:openbox]
command=openbox --display :99
autorestart=true
priority=15

[program:xsetroot]
command=xsetroot -solid black -display :99
autorestart=false
startsecs=0
priority=20

[program:x11vnc]
command=x11vnc -display :99 -forever -shared -nopw -noxrecord -noxfixes -noxdamage -q
autorestart=true
priority=30

[program:novnc]
command=websockify --web=/usr/share/novnc/ 8080 localhost:5900
autorestart=true
priority=40

[program:chrome]
command=google-chrome-stable --start-maximized --no-sandbox --disable-dev-shm-usage --no-default-browser-check --no-first-run --disable-infobars --disable-gpu --disable-smooth-scrolling --display=:99
autorestart=true
priority=50